POST http://localhost:5000/register HTTP/1.1
content-type: application/json

{
    "email": "fdsfdsds",
    "password": "dsfdsgetg"
}

###

POST http://localhost:5000/getcompanies HTTP/1.1
content-type: application/json

{
    "zanimanjeId": "5cf03e2793ee885981d515ff"
}

###

GET http://localhost:5000/logout HTTP/1.1

###

GET http://localhost:5000/checksession HTTP/1.1
