POST http://localhost:5000/gencaseone HTTP/1.1
content-type: application/json

{
    "fakultetId": "5cdec1dde96cf85787949292",
    "smjerId": "5cdec1dde96cf85787949293",
    "skolaId": "5cdebf15f88a0c5529953b7d",
    "zanimanjeId": "bf63bdd35bfea107408f28e1",
    "interesi": []
}